database: generated.sqlite
scenes: 30000
images: 4000000
galleries: 1500
chapters: 3000
markers: 3000
performers: 10000
studios: 1500
tags: 1500
naming:
  scenes: scene.txt
  performers:
    male: male.txt
    female: female.txt
    surname: surname.txt
  galleries: scene.txt
  studios: studio.txt
  tags: scene.txt
  images: scene.txt
